name: crud
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.4.3 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    rxdart: ^0.28.0
    http: ^1.2.2
    cupertino_icons: ^1.0.6
    equatable: ^2.0.5
    flutter_bloc: ^8.1.1
    flutter_dotenv: ^5.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
    assets:
        - .env
